### ISSUE TITLE
Relative module was not found error when using child components and SCSS

### ISSUE THREAD

**Issue by marijngiesen** [Toilal/vue-webpack-template#24]
I'm having problems using the template when I do the following:

* Switch to `scss` for my stylesheets (install sass-loader, etc)
* Add child component ExamView to my App component

`npm run dev` gives me:

```
 ERROR  Failed to compile with 1 errors                                                                               4:38:23 PM

This relative module was not found:

* ../../../node_modules/vue-template-loader/lib/scoped-style-loader.js?id=data-v-e949dba0!examview.scss in ./src/components/examview/examview.html?style=examview.scss
> Listening at http://localhost:8080
```

My `app.ts`:
```js
import Component from 'vue-class-component'
import WithRender from './app.html?style=app.scss'

import ExamView from './components/examview/examview'

@WithRender
@Component({
  components: {ExamView}
})
export default class App extends Vue {
}
```

My `examview.ts`:
```js
import Vue from 'vue'
import Component from 'vue-class-component'
import WithRender from './examview.html?style=examview.scss'

@WithRender
@Component
export default class ExamView extends Vue {
}
```
And my `app.html`:
```html
<div id="app">
  <examview></examview>
</div>
```

When I remove `ExamView` as child component of `App`, everything works fine.

**Comment by Toilal** [comment]
Style should also be prefixed with ./

Le 16 mai 2017 4:57 PM, "Marijn Giesen" <notifications@github.com> a écrit :

I'm having problems using the template when I do the following:

   - Switch to scss for my stylesheets (install sass-loader, etc)
   - Add child component ExamView to my App component

npm run dev gives me:

 ERROR  Failed to compile with 1 errors
                                               4:38:23 PM

This relative module was not found:

* ../../../node_modules/vue-template-loader/lib/scoped-style-loader.js?id=data-v-e949dba0!examview.scss
in ./src/components/examview/examview.html?style=examview.scss
> Listening at http://localhost:8080

My app.ts:

import Component from 'vue-class-component'import WithRender from
'./app.html?style=app.scss'
import ExamView from './components/examview/examview'

@WithRender
@Component({
  components: {ExamView}
})export default class App extends Vue {
}

My examview.ts:

import Vue from 'vue'import Component from 'vue-class-component'import
WithRender from './examview.html?style=examview.scss'

@WithRender
@Componentexport default class ExamView extends Vue {
}

And my app.html:

<div id="app">
  <examview></examview>
</div>

When I remove ExamView as child component of App, everything works fine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Toilal/vue-webpack-template/issues/24>, or mute the
thread

**Comment by marijngiesen** [comment]
Ah man, that was it. Sometimes it's just so easy ;)

Thanks!

**Comment by qugaopeng** [comment]
qqq

**Comment by jDover01** [comment]
where is the solution? I am facing the same issue. Thanks!
