### ISSUE TITLE
App.vue is not a module.

### ISSUE THREAD

**Issue by oguzhaneren** [Toilal/vue-webpack-template#62]
Hi,

Webpack build completed successfully, but throws one error after build:

![image](https://user-images.githubusercontent.com/2587216/35232533-bfa3f750-ffac-11e7-939a-596ea7327dfc.png)

Here my changed files after initiated template:

App.vue
```
<template src="./App.html">
</template>
<script  lang='ts' src="./App.ts"  >
</script>

<style src="./App.scss" lang="scss">
</style>
```
App.ts
```
import Vue from 'vue';
import Component from 'vue-class-component';
import axios from 'axios';

@Component
export default class App extends Vue {
   value: string;
   todos: Array<any>;

  created() {
    axios.get('http://jsonplaceholder.typicode.com/todos')
      .then(response => {
        this.todos = response.data;
      })
      .catch(error => {
        console.log(error);
      });
  }
}
```

**Comment by Toilal** [comment]
Thanks for reporting this issue, you only have to remove `.vue` extensions from import statements for now.

It's related to https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/94 and https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/88. It's fixed in master but still unreleased. I'll rollback this change when fork-ts-checker-webpack-plugin is released, so `.vue` extensions can be used just as with default TypeScript loader.
